# Generated by Django 4.2.2 on 2023-07-22 20:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "authorId",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "externalIds",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "affiliations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("paperCount", models.IntegerField(blank=True, null=True)),
                ("citationCount", models.IntegerField(blank=True, null=True)),
                ("hIndex", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PublicationVenue",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "alternate_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
