# Generated by Django 4.2.2 on 2023-06-13 23:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('externalIds', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('name', models.CharField(max_length=255)),
                ('affiliations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('paperCount', models.IntegerField()),
                ('citationCount', models.IntegerField()),
                ('hIndex', models.IntegerField()),
            ],
        ),
    ]
