# Generated by Django 4.2.2 on 2023-07-09 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_affiliations_alter_author_externalids'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('alternate_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
            ],
        ),
    ]
