# Generated by Django 4.2.2 on 2023-07-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='affiliation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
