# Generated by Django 4.2.2 on 2023-07-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="picture",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="media"
            ),
        ),
    ]
