# Generated by Django 4.2.2 on 2023-07-06 03:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_alter_author_affiliations_alter_author_externalids'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paperId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True, default='')),
                ('referenceCount', models.IntegerField()),
                ('citationCount', models.IntegerField()),
                ('openAccessPdf', models.URLField(blank=True, default='')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None)),
                ('tldr', models.TextField(blank=True, default='')),
                ('publicationDate', models.DateField()),
                ('authors', models.ManyToManyField(blank=True, related_name='papers', to='author.author')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='user.account')),
                ('papers', models.ManyToManyField(blank=True, default=list, related_name='libraries', to='paper.paper')),
                ('sharedWith', models.ManyToManyField(blank=True, default=list, related_name='sharedLibraries', to='user.account')),
            ],
        ),
    ]
