# Generated by Django 4.1.9 on 2023-06-13 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='user',
        ),
        migrations.AddField(
            model_name='paper',
            name='users_saved',
            field=models.ManyToManyField(blank=True, related_name='papers_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
