# Generated by Django 4.2.2 on 2023-07-05 09:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_affiliation'),
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='papers',
            field=models.ManyToManyField(blank=True, default=list, related_name='libraries', to='paper.paper'),
        ),
        migrations.AlterField(
            model_name='library',
            name='sharedWith',
            field=models.ManyToManyField(blank=True, default=list, related_name='sharedLibraries', to='user.account'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paper',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='paper',
            name='openAccessPdf',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paper',
            name='tldr',
            field=models.TextField(blank=True, default=''),
        ),
    ]
