# Generated by Django 4.2.2 on 2023-07-08 01:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_alter_library_papers_alter_library_sharedwith_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='fieldsOfStudy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
