# Generated by Django 4.2.2 on 2023-07-09 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_publicationvenue'),
        ('paper', '0003_paper_fieldsofstudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='publicationTypes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='paper',
            name='publicationVenue',
            field=models.ManyToManyField(blank=True, related_name='papers', to='author.publicationvenue'),
        ),
    ]
